### ISSUE TITLE
Spike: Reduce long load time

### ISSUE THREAD

**Issue by m-m-powers** [microsoft/wpa#16] opened 2020-12-02 15:34 UTC
**Is your feature request related to a problem? Please describe.**
Loading the {wpa} package takes upwards of 20 seconds sometimes, which is longer than other packages we use 

**Describe the solution you'd like**
Either speed up the load time (primary) or insert a status bar that shows progress (Secondary)

**Describe alternatives you've considered**
I can't get another work computer :(

**Additional context**

**Comment by martinctc** [comment] 2020-12-03 10:17
Thanks for logging this @m-m-powers! Have got two thoughts on why this might be the case:

1. Size of the demo datasets
2. Number of dependencies in the current package

Will need to investigate the cause for this - can I ask whether this slow load speed is with the latest GitHub version (v1.3.0)? Also, do you usually load **tidyverse** (or any other packages) before **wpa**, or vice versa? Are there any noticeable differences in load time?

**Comment by martinctc** [comment] 2020-12-17 22:02
New development: I've noticed that currently we use a number of duplicate packages for network graphing, i.e. 

- `network_g2g()`, `network_p2p()`
  -  **GGally**
  -  **network**
- `tm_cooc()`
  - **igraph**
  - **ggraph**
- `network_leiden()`, `network_louvain()` (experimental branch)
  - **igraph**
  - **ggraph**
- `track_HR_change()`
  - **networkD3**

There is potential for streamlining dependencies by migrating graphing packages from **GGally** / **network** set-up to the **igraph** / **ggraph** set-up. [Jesse Sadler's article](https://www.jessesadler.com/post/network-analysis-with-r/) makes an important point here:

> The network object classes for network, igraph, and tidygraph are all closely related. It is possible to translate between a network object and an igraph object. However, it is best to keep the two packages and their objects separate. In fact, the capabilities of network and igraph overlap to such an extent that it is best practice to have only one of the packages loaded at a time. 

It appears that the visual outputs can also be very well preserved regardless of the implementation:

_Output from **network** implementation_
![image](https://user-images.githubusercontent.com/17925865/102548988-58519f80-40b3-11eb-8ed2-c0cbcf9bf84c.png)

_Output from **igraph** implementation_
![image](https://user-images.githubusercontent.com/17925865/102548920-3f48ee80-40b3-11eb-820b-6795f3aa7e86.png)


I will open a pull request to begin this migration.

**Comment by martinctc** [comment] 2021-01-13 23:03
Non-essential dependencies have been removed at #36 to improve the load time - closing this issue.

**Closed by martinctc** 2021-01-13 23:03 UTC
Labels: spike
